### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by chelmerrox** [niicode/webpack-todo-app#4]
Excellent job! 🙂💯

- nice UI/UX.
- well-thought-out code. Good job!
- does everything that's required.

**Comment by soulemanou-software** [comment]
> Excellent job! 🙂💯
> 
> - nice UI/UX.
> - well-thought-out code. Good job!
> - does everything that's required.
###
> - Everything looks perfect for me but just need to add a live version, in the readme
